### ISSUE TITLE
AttributeError: 'list' object has no attribute 'encode'

### ISSUE THREAD

**Issue by bilgan** [Labelbox/Labelbox#88] opened 2018-07-06 06:45 UTC
I'm having an error on this line, which is that text is not a string its a list.

`text = text.encode('ascii')`

Please help. Thanks

**Comment by michel-meneses** [comment] 2018-07-17 00:07
I was having the same error. I figured out in my case I should export the labels as **WKT**, not CSV.

**Comment by feynmanliang** [comment] 2018-08-31 20:47
I think this may be a duplicate of #109 so I'm going to close this for now. If I'm mistaken, please let me know and provide repro instructions and I'll be happy to reopen!

**Closed by feynmanliang** 2018-08-31 20:47 UTC
