### ISSUE TITLE
Bad bounding box responsiveness

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#58] opened 2018-04-18 09:22 UTC
Guys, something have happened with bounding tool responsiveness about a week ago.
Initial setting of rectangular bounding box has now very bad responsiveness. Bounding box follows mouse pointer with delay. But when you set rectangular bounding box, changing it is very smooth.
Could you please look why changing rectangular bounding box is smooth when initially setting it is sloppy.

**Comment by valeriyvan** [comment] 2018-05-26 12:16
I am not even sure it got any better.

**Comment by manuaero** [comment] 2018-06-27 19:49
unable to reproduce. Closing for now. Please reopen this issue if you still see this issue.

**Closed by manuaero** 2018-06-27 19:49 UTC
Labels: bug
