### ISSUE TITLE
The order of data in ACTIVITY makes it hard to review or correct those recent annotations

### ISSUE THREAD

**Issue by SkyCASIA** [Labelbox/Labelbox#72] opened 2018-05-21 17:00 UTC
After the latest update, the order of labeled data in **ACTIVITY** makes it _difficult_ for our annotators to review their last annotations, and therefore causes unexpected trouble for annotators to correct their annotations ...

**Comment by valeriyvan** [comment] 2018-05-21 19:04
Duplicate of #71

**Comment by danielrasmuson** [comment] 2018-05-21 21:40
Thanks for bringing this up. We are working on a fix.

**Comment by danielrasmuson** [comment] 2018-05-22 04:34
Hi @SkyCASIA and @valeriyvan, we just pushed a fix for this issue. Feedback welcome.

**Closed by danielrasmuson** 2018-05-22 04:34 UTC
