### ISSUE TITLE
Error when exporting to COCO format

### ISSUE THREAD

**Issue by ztcuthbertlo** [Labelbox/Labelbox#108] opened 2018-08-27 22:10 UTC
After labeling and exported to WKT JSON file, result the following error message when running the python script to convert to COCO format. There is only one class label but multiple polygons in one image.

```
Traceback (most recent call last):
  File "json2coco.py", line 13, in <module>
    lb2co.from_json(labeled_data=labeled_data_train, coco_output=coco_output_train)
  File "Labelbox/scripts/labelbox2coco/__init__.py", line 79, in from_json
    multipolygon = wkt.loads(data['Label'][cat])
  File "/anaconda3/envs/labelbox/lib/python3.6/site-packages/shapely/wkt.py", line 10, in loads
    return geos.WKTReader(geos.lgeos).read(data)
  File "/anaconda3/envs/labelbox/lib/python3.6/site-packages/shapely/geos.py", line 250, in read
    text = text.encode('ascii')
AttributeError: 'list' object has no attribute 'encode'
```

**Comment by feynmanliang** [comment] 2018-08-28 00:52
Thanks for the bug report! I think this is a duplicate of #106 which we've recently pushed a fix for. I'm closing this issue; let's keep discussion on #106

**Closed by feynmanliang** 2018-08-28 00:52 UTC
